# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.runs/synth_1/DDS_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.cache/wt [current_project]
set_property parent.project_path C:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib C:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/hdl/DDS_wrapper.v
add_files C:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.srcs/sources_1/bd/DDS/DDS.bd
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_microblaze_0_1/DDS_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_microblaze_0_1/DDS_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_microblaze_0_1/DDS_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_clk_wiz_0_0/DDS_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_clk_wiz_0_0/DDS_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_clk_wiz_0_0/DDS_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_dlmb_v10_1/DDS_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_ilmb_v10_1/DDS_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_dlmb_bram_if_cntlr_1/DDS_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_ilmb_bram_if_cntlr_1/DDS_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_lmb_bram_1/DDS_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_mdm_1_1/DDS_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_mdm_1_1/DDS_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_rst_clk_wiz_0_100M_0/DDS_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_rst_clk_wiz_0_100M_0/DDS_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_rst_clk_wiz_0_100M_0/DDS_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_axi_uartlite_0_0/DDS_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_axi_uartlite_0_0/DDS_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_axi_uartlite_0_0/DDS_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_dds_compiler_0_1/DDS_dds_compiler_0_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_ila_0_0/DDS_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_c_addsub_0_0/DDS_c_addsub_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_dds_compiler_1_0/DDS_dds_compiler_1_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_ila_0_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_ila_0_1/DDS_ila_0_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_ila_2_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_ila_2_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_ila_2_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_ila_2_0/DDS_ila_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/DDS_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_microblaze_0_1/data/mb_bootloop_le.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.srcs/constrs_1/new/radio.xdc
set_property used_in_implementation false [get_files C:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.srcs/constrs_1/new/radio.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.srcs/utils_1/imports/synth_1/DDS_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top DDS_wrapper -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DDS_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file DDS_wrapper_utilization_synth.rpt -pb DDS_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
