# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/radio.xdc

# Block Designs: bd/DDS/DDS.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS || ORIG_REF_NAME==DDS} -quiet] -quiet

# IP: bd/DDS/ip/DDS_microblaze_0_1/DDS_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_microblaze_0_1 || ORIG_REF_NAME==DDS_microblaze_0_1} -quiet] -quiet

# IP: bd/DDS/ip/DDS_clk_wiz_0_0/DDS_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_clk_wiz_0_0 || ORIG_REF_NAME==DDS_clk_wiz_0_0} -quiet] -quiet

# IP: bd/DDS/ip/DDS_dlmb_v10_1/DDS_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_dlmb_v10_1 || ORIG_REF_NAME==DDS_dlmb_v10_1} -quiet] -quiet

# IP: bd/DDS/ip/DDS_ilmb_v10_1/DDS_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_ilmb_v10_1 || ORIG_REF_NAME==DDS_ilmb_v10_1} -quiet] -quiet

# IP: bd/DDS/ip/DDS_dlmb_bram_if_cntlr_1/DDS_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==DDS_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/DDS/ip/DDS_ilmb_bram_if_cntlr_1/DDS_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==DDS_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/DDS/ip/DDS_lmb_bram_1/DDS_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_lmb_bram_1 || ORIG_REF_NAME==DDS_lmb_bram_1} -quiet] -quiet

# IP: bd/DDS/ip/DDS_mdm_1_1/DDS_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_mdm_1_1 || ORIG_REF_NAME==DDS_mdm_1_1} -quiet] -quiet

# IP: bd/DDS/ip/DDS_rst_clk_wiz_0_100M_0/DDS_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==DDS_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/DDS/ip/DDS_axi_uartlite_0_0/DDS_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_axi_uartlite_0_0 || ORIG_REF_NAME==DDS_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/DDS/ip/DDS_microblaze_0_axi_periph_0/DDS_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_microblaze_0_axi_periph_0 || ORIG_REF_NAME==DDS_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/DDS/ip/DDS_dds_compiler_0_1/DDS_dds_compiler_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_dds_compiler_0_1 || ORIG_REF_NAME==DDS_dds_compiler_0_1} -quiet] -quiet

# IP: bd/DDS/ip/DDS_ila_0_0/DDS_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_ila_0_0 || ORIG_REF_NAME==DDS_ila_0_0} -quiet] -quiet

# IP: bd/DDS/ip/DDS_c_addsub_0_0/DDS_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_c_addsub_0_0 || ORIG_REF_NAME==DDS_c_addsub_0_0} -quiet] -quiet

# IP: bd/DDS/ip/DDS_dds_compiler_1_0/DDS_dds_compiler_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_dds_compiler_1_0 || ORIG_REF_NAME==DDS_dds_compiler_1_0} -quiet] -quiet

# IP: bd/DDS/ip/DDS_ila_0_1/DDS_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_ila_0_1 || ORIG_REF_NAME==DDS_ila_0_1} -quiet] -quiet

# IP: bd/DDS/ip/DDS_ila_2_0/DDS_ila_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_ila_2_0 || ORIG_REF_NAME==DDS_ila_2_0} -quiet] -quiet

# XDC: c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/DDS_ooc.xdc
