# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.srcs/sources_1/bd/DDS/ip/DDS_mult_gen_0_0/DDS_mult_gen_0_0.xci
# IP: The module: 'DDS_mult_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_mult_gen_0_0/DDS_mult_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDS_mult_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.srcs/sources_1/bd/DDS/ip/DDS_mult_gen_0_0/DDS_mult_gen_0_0.xci
# IP: The module: 'DDS_mult_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danny/Downloads/Projects/FMTransmitter/FMTransmitter.gen/sources_1/bd/DDS/ip/DDS_mult_gen_0_0/DDS_mult_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDS_mult_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
